/*
 * FouleFactoryApi.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FouleFactoryApi.PCL;

namespace FouleFactoryApi.PCL.Models
{
    public class AccountWriterServiceModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int idGender;
        private string firstName;
        private string name;
        private string email;
        private string phone;
        private DateTime birthday;
        private string address1;
        private string city;
        private string postalCode;
        private string countryCode;
        private string nationality;
        private bool optin;
        private string company;
        private string address2;
        private string billAddress1;
        private string billAddress2;
        private string billCity;
        private string billPostalCode;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IdGender")]
        public int IdGender 
        { 
            get 
            {
                return this.idGender; 
            } 
            set 
            {
                this.idGender = value;
                onPropertyChanged("IdGender");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("FirstName")]
        public string FirstName 
        { 
            get 
            {
                return this.firstName; 
            } 
            set 
            {
                this.firstName = value;
                onPropertyChanged("FirstName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Phone")]
        public string Phone 
        { 
            get 
            {
                return this.phone; 
            } 
            set 
            {
                this.phone = value;
                onPropertyChanged("Phone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Birthday")]
        public DateTime Birthday 
        { 
            get 
            {
                return this.birthday; 
            } 
            set 
            {
                this.birthday = value;
                onPropertyChanged("Birthday");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Address1")]
        public string Address1 
        { 
            get 
            {
                return this.address1; 
            } 
            set 
            {
                this.address1 = value;
                onPropertyChanged("Address1");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("City")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PostalCode")]
        public string PostalCode 
        { 
            get 
            {
                return this.postalCode; 
            } 
            set 
            {
                this.postalCode = value;
                onPropertyChanged("PostalCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CountryCode")]
        public string CountryCode 
        { 
            get 
            {
                return this.countryCode; 
            } 
            set 
            {
                this.countryCode = value;
                onPropertyChanged("CountryCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Nationality")]
        public string Nationality 
        { 
            get 
            {
                return this.nationality; 
            } 
            set 
            {
                this.nationality = value;
                onPropertyChanged("Nationality");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Optin")]
        public bool Optin 
        { 
            get 
            {
                return this.optin; 
            } 
            set 
            {
                this.optin = value;
                onPropertyChanged("Optin");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Company")]
        public string Company 
        { 
            get 
            {
                return this.company; 
            } 
            set 
            {
                this.company = value;
                onPropertyChanged("Company");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Address2")]
        public string Address2 
        { 
            get 
            {
                return this.address2; 
            } 
            set 
            {
                this.address2 = value;
                onPropertyChanged("Address2");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillAddress1")]
        public string BillAddress1 
        { 
            get 
            {
                return this.billAddress1; 
            } 
            set 
            {
                this.billAddress1 = value;
                onPropertyChanged("BillAddress1");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillAddress2")]
        public string BillAddress2 
        { 
            get 
            {
                return this.billAddress2; 
            } 
            set 
            {
                this.billAddress2 = value;
                onPropertyChanged("BillAddress2");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillCity")]
        public string BillCity 
        { 
            get 
            {
                return this.billCity; 
            } 
            set 
            {
                this.billCity = value;
                onPropertyChanged("BillCity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillPostalCode")]
        public string BillPostalCode 
        { 
            get 
            {
                return this.billPostalCode; 
            } 
            set 
            {
                this.billPostalCode = value;
                onPropertyChanged("BillPostalCode");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 