/*
 * FouleFactoryApi.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FouleFactoryApi.PCL;

namespace FouleFactoryApi.PCL.Models
{
    public class CsvFileWriterServiceModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int idProject;
        private string file;
        private bool header;
        private string separator;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IdProject")]
        public int IdProject 
        { 
            get 
            {
                return this.idProject; 
            } 
            set 
            {
                this.idProject = value;
                onPropertyChanged("IdProject");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("File")]
        public string File 
        { 
            get 
            {
                return this.file; 
            } 
            set 
            {
                this.file = value;
                onPropertyChanged("File");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Header")]
        public bool Header 
        { 
            get 
            {
                return this.header; 
            } 
            set 
            {
                this.header = value;
                onPropertyChanged("Header");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Separator")]
        public string Separator 
        { 
            get 
            {
                return this.separator; 
            } 
            set 
            {
                this.separator = value;
                onPropertyChanged("Separator");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 