/*
 * FouleFactoryApi.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FouleFactoryApi.PCL;

namespace FouleFactoryApi.PCL.Models
{
    public class ProjectWriterServiceModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int idTemplate;
        private string title;
        private string estimatedTimePerTask;
        private int nbSupplierPerTask;
        private int amountWithoutTaxPerTask;
        private bool automaticValidation;
        private DateTime? maxEndDate;
        private int? idCertification;
        private string urlNotification;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IdTemplate")]
        public int IdTemplate 
        { 
            get 
            {
                return this.idTemplate; 
            } 
            set 
            {
                this.idTemplate = value;
                onPropertyChanged("IdTemplate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("EstimatedTimePerTask")]
        public string EstimatedTimePerTask 
        { 
            get 
            {
                return this.estimatedTimePerTask; 
            } 
            set 
            {
                this.estimatedTimePerTask = value;
                onPropertyChanged("EstimatedTimePerTask");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("NbSupplierPerTask")]
        public int NbSupplierPerTask 
        { 
            get 
            {
                return this.nbSupplierPerTask; 
            } 
            set 
            {
                this.nbSupplierPerTask = value;
                onPropertyChanged("NbSupplierPerTask");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AmountWithoutTaxPerTask")]
        public int AmountWithoutTaxPerTask 
        { 
            get 
            {
                return this.amountWithoutTaxPerTask; 
            } 
            set 
            {
                this.amountWithoutTaxPerTask = value;
                onPropertyChanged("AmountWithoutTaxPerTask");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AutomaticValidation")]
        public bool AutomaticValidation 
        { 
            get 
            {
                return this.automaticValidation; 
            } 
            set 
            {
                this.automaticValidation = value;
                onPropertyChanged("AutomaticValidation");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MaxEndDate")]
        public DateTime? MaxEndDate 
        { 
            get 
            {
                return this.maxEndDate; 
            } 
            set 
            {
                this.maxEndDate = value;
                onPropertyChanged("MaxEndDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IdCertification")]
        public int? IdCertification 
        { 
            get 
            {
                return this.idCertification; 
            } 
            set 
            {
                this.idCertification = value;
                onPropertyChanged("IdCertification");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("UrlNotification")]
        public string UrlNotification 
        { 
            get 
            {
                return this.urlNotification; 
            } 
            set 
            {
                this.urlNotification = value;
                onPropertyChanged("UrlNotification");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 