/*
 * FouleFactoryApi.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FouleFactoryApi.PCL;

namespace FouleFactoryApi.PCL.Models
{
    public class TemplateNewWriterServiceModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int idProjectType;
        private string title;
        private string description;
        private List<TemplateInstructionWriterServiceModel> instructions;
        private List<TemplateColumnWriterServiceModel> columns;
        private List<TemplateQuestionWriterServiceModel> questions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IdProjectType")]
        public int IdProjectType 
        { 
            get 
            {
                return this.idProjectType; 
            } 
            set 
            {
                this.idProjectType = value;
                onPropertyChanged("IdProjectType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Instructions")]
        public List<TemplateInstructionWriterServiceModel> Instructions 
        { 
            get 
            {
                return this.instructions; 
            } 
            set 
            {
                this.instructions = value;
                onPropertyChanged("Instructions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Columns")]
        public List<TemplateColumnWriterServiceModel> Columns 
        { 
            get 
            {
                return this.columns; 
            } 
            set 
            {
                this.columns = value;
                onPropertyChanged("Columns");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Questions")]
        public List<TemplateQuestionWriterServiceModel> Questions 
        { 
            get 
            {
                return this.questions; 
            } 
            set 
            {
                this.questions = value;
                onPropertyChanged("Questions");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 