/*
 * FouleFactoryApi.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using FouleFactoryApi.PCL;

namespace FouleFactoryApi.PCL.Models
{
    public class TemplateQuestionWriterServiceModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string title;
        private bool require;
        private int idTemplateObjectQuestionType;
        private int order;
        private string option;
        private List<string> choices;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Require")]
        public bool Require 
        { 
            get 
            {
                return this.require; 
            } 
            set 
            {
                this.require = value;
                onPropertyChanged("Require");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IdTemplateObjectQuestionType")]
        public int IdTemplateObjectQuestionType 
        { 
            get 
            {
                return this.idTemplateObjectQuestionType; 
            } 
            set 
            {
                this.idTemplateObjectQuestionType = value;
                onPropertyChanged("IdTemplateObjectQuestionType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Order")]
        public int Order 
        { 
            get 
            {
                return this.order; 
            } 
            set 
            {
                this.order = value;
                onPropertyChanged("Order");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Option")]
        public string Option 
        { 
            get 
            {
                return this.option; 
            } 
            set 
            {
                this.option = value;
                onPropertyChanged("Option");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Choices")]
        public List<string> Choices 
        { 
            get 
            {
                return this.choices; 
            } 
            set 
            {
                this.choices = value;
                onPropertyChanged("Choices");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 